name: CI

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[maven-release-plugin] prepare') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    name: Build on Java ${{ matrix.java }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64

      - run: java -version
      - run: mvn -v
      - run: mvn -B verify -Dgpg.skip=true

  release:
    if: contains(github.ref, 'release') && startsWith(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    needs: [build]
    name: Release
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set env.BRANCH_NAME
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Release and Publish
        uses: qcastel/github-actions-maven-release@v1.12.25
        with:
          release-branch-name: ${{ env.BRANCH_NAME }}
          maven-args: "-DskipTests -DskipITs"

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"
          git-skip-sanity-check: true

          maven-repo-server-id: ossrh
          maven-repo-server-username: ${{ secrets.GITHUB_USER }}
          maven-repo-server-password: ${{ secrets.MAVEN_ACCESS_TOKEN }}
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
